### PR TITLE
Add support for custom fields + generation parameters

### LINKED ISSUE #3: New release with gnark-crypto support
When you have a moment, would be nice to get a tagged release for https://github.com/triplewz/poseidon/commit/5265fab9d889e515be3683f47bea734a80740c3f (gnark-crypto support).

### PR DESCRIPTION
**Pull request by mdehoog**
Firstly thank you for your poseidon implementation, I've found it very helpful personally.

This PR adds support for passing in custom field elements from the gnark-crypto library as a generic argument. This means any curve can be used, not just BLS12-381.

Secondly, it adds the ability to pass in custom values for `rp`, `rf`, `field`, `sbox`, and the `mds` matrix to the constant generation function. I've been able to reproduce the circom's [constants](https://github.com/iden3/circomlib/blob/master/circuits/poseidon_constants.circom) exactly when using `field=1`, `sbox=0`, and `rp` / `rf` / `mds` values calculated by https://extgit.iaik.tugraz.at/krypto/hadeshash/-/blob/master/code/generate_params_poseidon.sage (with a minor modification to round up `rp` to the nearest multiple of `width`).

Totally understandable if this major refactor is outside the scope of this repo, I'd be happy to maintain a fork if preferred.

### CODE REVIEW

**Comment by triplewz** [comment]
hi, @mdehoog, thanks for your work, I'll review the code as soon as possible.

**Comment by triplewz** [comment]
@vmx hi, could you help to review the code?

**Review by vmx — COMMENTED** [review]
This looks like a straight forward refactor, hence sounds good to me. But please note that I'm not really a Go coder.

**Comment by triplewz** [comment]
> This looks like a straight forward refactor, hence sounds good to me. But please note that I'm not really a Go coder.

Thanks.

**Comment by triplewz** [comment]
@mdehoog plz check the github workflow. Thanks.

**Comment by mdehoog** [comment]
@triplewz thanks for the review! Removed the tests from the workflow 👍

**Pull request merged**
